customhost = "employeedb.cphulrovocta.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "ekangaki1234"
customdb = "employeedb"
custombucket = "afro-employee-bucket"
customregion = "us-east-1"
